.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. learncoin_qt test_learncoin_qt
clean: FORCE
	$(MAKE) -C .. learncoin_qt_clean test_learncoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_learncoin_qt_check
learncoin-qt learncoin-qt.exe: FORCE
	 $(MAKE) -C .. learncoin_qt
